# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-14 09:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_time', models.DateTimeField(default=False, verbose_name='比对时间')),
                ('result', models.BooleanField(default=True, verbose_name='比对结果')),
                ('raw_material1', models.CharField(default='', max_length=50, verbose_name='物料1')),
                ('raw_material2', models.CharField(default='', max_length=50, verbose_name='物料2')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Order_list', verbose_name='订单')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='生产员工')),
            ],
            options={
                'verbose_name': '比对记录',
                'verbose_name_plural': '比对记录',
                'db_table': 'recode',
            },
        ),
    ]
